"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { AlertTriangle, ArrowLeft, CheckCircle2, CircleHelp, ExternalLink, FileText, MinusCircle, ShieldCheck, XCircle } from "lucide-react";
import { api, API_URL, Run, Submission, dateLabel } from "@/lib/api";

export default function ReportPage(){const params=useParams<{id:string}>();const[id,setId]=useState<Run|null>(null);const[item,setItem]=useState<Submission|null>(null);const[error,setError]=useState("");useEffect(()=>{api<Run>(`/api/runs/${params.id}`).then(async run=>{setId(run);try{setItem(await api<Submission>(`/api/submissions/${run.submission_id}`));}catch{}}).catch(e=>setError(e.message));},[params.id]);
 if(error)return <><div className="eyebrow">REPORT / ERROR</div><h1 className="page-title">Report unavailable</h1><div className="error-banner">{error}</div><Link className="text-link" href="/submissions">Back to submissions</Link></>;
 if(!id)return <><div className="eyebrow">REPORT / EVIDENCE REVIEW</div><h1 className="page-title">Preparing the report…</h1><div className="skeleton"/></>;
 if(id.status!=="completed"||!id.report)return <><div className="eyebrow">REPORT / EVIDENCE REVIEW</div><h1 className="page-title">This judge run is {id.status}.</h1><p className="page-subtitle">{id.phase} · {id.progress}%</p><div className="progress-track" style={{marginTop:18}}><div className="progress-fill" style={{width:`${id.progress}%`}}/></div>{id.error_message&&<div className="error-banner">{id.error_message}</div>}<Link className="text-link" href={`/submissions/${id.submission_id}`} style={{marginTop:17}}>Return to project <ArrowLeft size={13}/></Link></>;
 const report=id.report;const criteria=report.criteria||[];const observations=id.observations||report.all_observations||[];const evidence=id.evidence||report.evidence||[];const tests=[...(report.passed_tests||[]),...(report.failed_tests||[])];
 return <><div className="eyebrow">JUDGE RUN / REPORT</div><div className="header-row" style={{marginTop:6,marginBottom:15,alignItems:"center"}}><div><div style={{display:"flex",alignItems:"center",gap:9}}><Link href={`/submissions/${id.submission_id}`} className="secondary-btn" style={{padding:8}} aria-label="Back to project"><ArrowLeft size={14}/></Link><h1 className="page-title" style={{margin:0}}>{item?.project_name||"Evaluation report"}</h1></div><p className="page-subtitle" style={{margin:"6px 0 0 38px"}}>Application ID {item?.application_number||"—"} · Evaluated {dateLabel(id.completed_at)} · Run {id.id.slice(0,8)}</p></div><div style={{display:"flex",gap:8}}>{item?.source_pdf_available&&<a className="secondary-btn" href={`${API_URL}/api/submissions/${item.id}/source-pdf`} target="_blank" rel="noreferrer">Source PDF <FileText size={12}/></a>}<a className="secondary-btn" href={item?.deployed_url} target="_blank" rel="noreferrer">Live app <ExternalLink size={12}/></a></div></div>
    <div className="detail-hero"><div><div className="eyebrow" style={{color:"#a9c1b6",marginBottom:9}}>CHIEF JUDGE SUMMARY</div><h1>Evidence-led evaluation</h1><p>The score follows the published weighted rubric. Every browser finding below comes from this run’s recorded observations.</p><p style={{fontSize:11,color:"#d0ddd7",marginTop:8}}>Scoring mode: {report.evaluation_mode||"Legacy deterministic heuristic (pre-audit; not AI-validated)"}{report.score_status==="provisional_requires_human_review"||!report.evaluation_mode?" · Provisional, human review required":""}</p></div><div className="detail-score"><strong>{report.total_score?.toFixed(1)}</strong><span> /100</span><div className="confidence" style={{justifyContent:"flex-end",marginTop:7}}><span className="confidence-track"><span style={{width:`${report.confidence}%`}}/></span><span style={{fontSize:9,color:"#c3d6ce"}}>{report.confidence}% confidence</span></div></div></div>
    {!!report.review_flags?.length&&<section className="panel" style={{marginBottom:13}}><div className="panel-heading"><div className="panel-title" style={{display:"flex",alignItems:"center",gap:7,color:"#8a6539"}}><AlertTriangle size={14}/> Human review recommended</div><span className="panel-kicker">{report.review_flags.length} FLAG{report.review_flags.length===1?"":"S"}</span></div><div className="flag-list">{report.review_flags.map((flag:string,index:number)=><div className="review-flag" key={index}><CircleHelp size={13}/>{flag}</div>)}</div></section>}
    <div className="report-grid"><div className="report-left"><section className="panel"><div className="panel-heading"><div><div className="panel-title">Criterion scores</div><div className="panel-kicker" style={{marginTop:4}}>Weighted rubric · 100 points total</div></div><span className="status-pill complete">TOTAL &nbsp;{report.total_score?.toFixed(1)} / 100</span></div><div className="criterion-list">{criteria.map((c:any)=><div className="criterion-card" key={c.key}><div className="criterion-top"><span className="criterion-name">{c.name}</span><span className="criterion-weight">{c.weight}% weight</span><span className="criterion-points">{Number(c.score).toFixed(1)}<small style={{fontSize:8,color:"#99a49e"}}> / {c.max_points}</small></span></div><div className="criterion-sub"><div className="criterion-track"><span style={{width:`${Math.max(0,Math.min(100,Number(c.raw_score)*10))}%`}}/></div><small>{c.raw_score}/10</small></div><p className="criterion-rationale">{c.rationale}</p>{c.points_not_awarded>0&&<div className="test-detail" style={{marginTop:9,padding:"9px 10px",borderRadius:6,background:"#fff8f1",color:"#815c43"}}><b>{Number(c.points_not_awarded).toFixed(1)} points not awarded:</b> {c.why_points_not_awarded}</div>}{c.evidence_ids?.length>0&&<div className="criterion-evidence">OBSERVATIONS &nbsp;{c.evidence_ids.slice(0,6).join(" · ")}{c.evidence_ids.length>6?` · +${c.evidence_ids.length-6}`:""}</div>}{c.strengths?.length>0&&<div className="criterion-evidence" style={{color:"#377b61"}}>STRENGTH &nbsp;{c.strengths.join(" · ")}</div>}</div>)}</div><div className="footer-note">Assessment source: {report.evaluation_mode||"Not recorded"}. AI/vibe-coding usage is not scored.</div></section>
      <section className="panel"><div className="panel-heading"><div><div className="panel-title">Test results</div><div className="panel-kicker" style={{marginTop:4}}>Actual outcomes recorded by the browser worker</div></div><span className="panel-kicker">{tests.length} RESULT{tests.length===1?"":"S"}</span></div>{tests.length?<div className="test-list">{tests.map((test:any,index:number)=><div className="test-row" key={`${test.id}-${index}`}><span className="test-icon">{test.result==="passed"?<CheckCircle2 size={14} color="#43876c"/>:<XCircle size={14} color="#c16b56"/>}</span><div style={{flex:1,minWidth:0}}><div className="test-title">{test.title}<span className="observation-id">{test.id}</span></div><div className="test-detail">{test.detail}</div></div><span className={`test-tag ${test.result}`}>{test.result.toUpperCase()}</span></div>)}</div>:<div className="empty-state" style={{minHeight:85}}>No tests produced a definitive pass/fail result in this run.</div>}</section>
      <section className="panel"><div className="panel-heading"><div><div className="panel-title">Observation log</div><div className="panel-kicker" style={{marginTop:4}}>What the browser actually saw</div></div><span className="panel-kicker">{observations.length} EVENTS</span></div><div className="observation-list">{observations.map((obs:any,index:number)=><div className="observation-row" key={`${obs.id}-${index}`}><b>{obs.title}<span className="observation-id">{obs.id}</span></b><p>{obs.detail}</p></div>)}</div></section></div>
      <div className="report-right"><section className="panel"><div className="panel-heading"><div className="panel-title">Evidence gallery</div><span className="panel-kicker">{evidence.length} FILES</span></div>{evidence.filter((e:any)=>e.kind==="screenshot").length?<div className="evidence-grid">{evidence.filter((e:any)=>e.kind==="screenshot").map((e:any)=><a href={`${API_URL}/api/runs/${id.id}/evidence/${encodeURIComponent(e.file)}`} target="_blank" rel="noreferrer" key={e.id}><img className="evidence-image" src={`${API_URL}/api/runs/${id.id}/evidence/${encodeURIComponent(e.file)}`} alt={e.title}/><div className="evidence-caption">{e.title}</div></a>)}</div>:<div className="empty-state" style={{minHeight:90}}>No screenshots were captured.</div>}</section>
      <section className="panel"><div className="panel-heading"><div className="panel-title">Strengths</div><CheckCircle2 size={14} color="#468b6e"/></div><div className="bullet-list">{(report.strengths||[]).map((text:string,i:number)=><div className="bullet-row" key={i}><CheckCircle2 size={13}/>{text}</div>)}</div></section>
      <section className="panel"><div className="panel-heading"><div className="panel-title">Weaknesses & limitations</div><MinusCircle size={14} color="#b97a59"/></div><div className="bullet-list">{(report.weaknesses||[]).map((text:string,i:number)=><div className="bullet-row weak" key={i}><MinusCircle size={13}/>{text}</div>)}</div></section>
      <section className="panel"><div className="panel-heading"><div className="panel-title">Bias audit</div><ShieldCheck size={14} color="#468b6e"/></div><div className="panel-kicker" style={{marginBottom:10}}>{report.bias_audit?.status?.toUpperCase()||"REVIEW"}</div><div className="bullet-list">{(report.bias_audit?.checks||[]).map((text:string,i:number)=><div className="bullet-row" key={i}><CheckCircle2 size={12}/>{text}</div>)}</div></section>
      {!!report.anti_gaming_checks?.length&&<section className="panel"><div className="panel-heading"><div className="panel-title">Anti-gaming review signals</div><AlertTriangle size={14} color="#b97a59"/></div><div className="bullet-list">{report.anti_gaming_checks.map((check:any,i:number)=><div className="bullet-row weak" key={i}><CircleHelp size={12}/><span><b>{check.signal}</b><br/>{check.detail}<small className="observation-id">{check.observation_id}</small></span></div>)}</div><div className="footer-note">Signals identify evidence gaps or unusual behavior for a person to review; they do not establish intentional gaming.</div></section>}
      {!!report.deductions?.length&&<section className="panel"><div className="panel-heading"><div className="panel-title">Deductions</div><AlertTriangle size={14} color="#b97a59"/></div><div className="bullet-list">{report.deductions.map((d:any,i:number)=><div className="bullet-row weak" key={i}><MinusCircle size={12}/><span>{d.reason} <small style={{color:"#9ba49f"}}>· {d.points!=null?`−${Number(d.points).toFixed(1)} points allocated`:"score impact shown above"}; reflected in criterion score</small></span></div>)}</div></section>}</div></div>
    <div className="footer-note">Browser actions and screenshots are observations. The scoring mode and review flags above show how the criteria were assessed and which judgments need human review. Untested behavior is not treated as proven.</div>
  </>;
}
