"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, ExternalLink, FileText, Github, Globe2, Play, RefreshCw, ShieldCheck } from "lucide-react";
import { api, API_URL, Run, Submission, dateLabel } from "@/lib/api";

export default function SubmissionDetail(){
  const params=useParams<{id:string}>();const id=params.id;const [item,setItem]=useState<Submission|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  const refresh=useCallback(()=>api<Submission>(`/api/submissions/${id}`).then(setItem).catch(e=>setError(e.message)),[id]);
  useEffect(()=>{refresh();const interval=setInterval(refresh,2500);return()=>clearInterval(interval);},[refresh]);
  useEffect(()=>{if(!error)return;const timeout=setTimeout(()=>setError(""),5000);return()=>clearTimeout(timeout);},[error]);
  async function start(){setBusy(true);setError("");try{await api<Run>(`/api/submissions/${id}/judge`,{method:"POST"});await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not start judge.");}finally{setBusy(false);}}
  if(!item)return <><div className="eyebrow">SUBMISSIONS / PROJECT</div><h1 className="page-title">Loading project…</h1>{error&&<div className="error-banner">{error}</div>}<div className="skeleton"/></>;
  const run=item.latest_run;const done=run?.status==="completed";
  return <><div className="eyebrow">PROJECTS / PROJECT DETAIL</div><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginTop:8,gap:12}}><div style={{display:"flex",alignItems:"center",gap:10}}><Link href="/submissions" className="secondary-btn" style={{padding:8}} aria-label="Back"><ArrowLeft size={14}/></Link><div><h1 className="page-title" style={{margin:0}}>{item.project_name}</h1><p className="page-subtitle" style={{marginTop:4}}>Application ID {item.application_number||"—"} · Submitted {dateLabel(item.created_at)}</p></div></div><div style={{display:"flex",gap:8}}><a className="secondary-btn" href={item.deployed_url} target="_blank" rel="noreferrer"><Globe2 size={14}/> Open live app <ExternalLink size={12}/></a>{item.github_url&&<a className="secondary-btn" href={item.github_url} target="_blank" rel="noreferrer"><Github size={14}/> Repository</a>}</div></div>
    {error&&<div className="error-banner">{error}</div>}
    <div className="detail-hero"><div><div className="eyebrow" style={{color:"#a9c1b6",marginBottom:9}}>AUTONOMOUS BROWSER JUDGE</div><h1>{done?"Your evaluation is ready.":run?.status==="running"?"Judge is exploring the app.":run?.status==="queued"?"Your project is in the queue.":run?.status==="failed"?"This judge run needs attention.":"Ready when you are."}</h1><p>{done?"Review the report, browser observations, and captured evidence.":run?.status==="running"?"Playwright is collecting evidence from the deployed URL.":"The judge opens the deployed URL and tests what it can observe."}</p></div><div className="detail-score">{done?<><strong>{run.total_score?.toFixed(1)}</strong><span> /100</span><div style={{fontSize:9,color:"#b5c9c0",marginTop:5}}>Confidence {run.confidence}%</div></>:<button className="primary-btn" disabled={busy} onClick={start} style={{background:"#f2f7f3",color:"#194d3e"}}>{busy?<RefreshCw size={14} className="spin"/>:<Play size={14}/>} {busy?"Starting…":run?.status==="running"||run?.status==="queued"?"Re-evaluate":"Start judging"}</button>}</div></div>
    {run&&["queued","running"].includes(run.status)&&<div className="panel job-card"><div className="job-title-row"><span className="job-phase">{run.phase}</span><span className="job-percent">{run.progress}%</span></div><div className="progress-track"><div className="progress-fill" style={{width:`${run.progress}%`}}/></div><div className="footer-note" style={{border:0,marginTop:9,padding:0}}>Projects enter the evaluation queue on submission and start when a judge worker slot is available. Interrupted jobs return to the queue automatically.</div></div>}
    {run?.status==="failed"&&<div className="error-banner">{run.error_message||"The judging job failed."} <button onClick={start} className="text-link" style={{border:0,background:"transparent",marginLeft:8}}>Retry <RefreshCw size={12}/></button></div>}
    <div className="dashboard-grid" style={{alignItems:"start",marginTop:14}}><section className="panel"><div className="panel-heading"><div><div className="panel-title">Project details</div><div className="panel-kicker" style={{marginTop:4}}>Extracted from the uploaded PDF</div></div><FileText size={15} color="#97a59d"/></div><div className="section-title" style={{fontSize:10}}>Project name</div><p className="page-subtitle" style={{lineHeight:1.7,margin:"6px 0 17px",color:"#616f67"}}>{item.project_name}</p><div className="section-title" style={{fontSize:10}}>Participant name</div><p className="page-subtitle" style={{lineHeight:1.7,margin:"6px 0 17px",color:"#616f67"}}>{item.participant_names[0]}</p><div className="section-title" style={{fontSize:10}}>Problem statement</div><p className="page-subtitle" style={{lineHeight:1.7,margin:"6px 0 17px",color:"#616f67"}}>{item.problem_statement}</p><div className="section-title" style={{fontSize:10}}>Description</div><p className="page-subtitle" style={{lineHeight:1.7,margin:"6px 0 4px",color:"#616f67"}}>{item.solution_description}</p></section>
      <section className="panel"><div className="panel-heading"><div><div className="panel-title">Project links</div><div className="panel-kicker" style={{marginTop:4}}>ID {item.application_number||"—"}</div></div><Globe2 size={15} color="#97a59d"/></div><div className="info-list"><div className="info-row"><Globe2 size={13}/><a href={item.deployed_url} target="_blank" rel="noreferrer" style={{overflowWrap:"anywhere"}}>{item.deployed_url}</a></div>{item.source_pdf_available&&<div className="info-row"><FileText size={13}/><a href={`${API_URL}/api/submissions/${item.id}/source-pdf`} target="_blank" rel="noreferrer">View uploaded PDF</a></div>}{item.github_url&&<div className="info-row"><Github size={13}/><a href={item.github_url} target="_blank" rel="noreferrer">Public repository</a></div>}</div><div className="footer-note"><ShieldCheck size={12} style={{verticalAlign:"middle",marginRight:5}}/>Individual project entry.</div></section>
    </div>
    {done&&<div className="success-banner" style={{marginTop:13,display:"flex",alignItems:"center",justifyContent:"space-between"}}>The evidence-backed report is ready. <Link className="text-link" href={`/reports/${run.id}`}>Open evaluation report <ArrowRight size={13}/></Link></div>}
  </>;
}
