"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { ArrowRight, Medal, ShieldCheck, Trophy } from "lucide-react";
import { api, Leader } from "@/lib/api";

export default function LeaderboardPage(){const[rows,setRows]=useState<Leader[]>([]);const[error,setError]=useState("");const refresh=useCallback(()=>api<Leader[]>("/api/leaderboard").then(data=>{setRows(data);setError("");}).catch(e=>setError(e.message)),[]);useEffect(()=>{refresh();const timer=window.setInterval(refresh,5000);return()=>window.clearInterval(timer);},[refresh]);
 return <><div className="header-row"><div><div className="eyebrow">RESULTS / RANKINGS</div><h1 className="page-title">Leaderboard</h1><p className="page-subtitle">Latest completed score per project across the published criteria.</p></div><span className="status-pill complete"><Trophy size={12}/> {rows.length} SCORED</span></div>{error&&<div className="error-banner">Could not load leaderboard: {error}</div>}
   <div className="panel"><div className="panel-heading"><div><div className="panel-title">Project rankings</div><div className="panel-kicker" style={{marginTop:4}}>Ties break by the earlier completed evaluation</div></div><span className="panel-kicker">OUT OF 100</span></div>{rows.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>RANK</th><th>APPLICATION ID</th><th>PROJECT</th><th>PARTICIPANTS</th><th>CONFIDENCE</th><th>REVIEW</th><th>SCORE</th><th></th></tr></thead><tbody>{rows.map(row=><tr key={row.run_id}><td className={`leader-rank ${row.rank===1?"rank-first":""}`}><span style={{display:"inline-flex",alignItems:"center",gap:6}}>{row.rank===1&&<Medal size={13}/>} {String(row.rank).padStart(2,"0")}</span></td><td>{row.application_number||"—"}</td><td><Link className="project-cell" href={`/reports/${row.run_id}`}><span className="project-avatar">{row.project_name.slice(0,1).toUpperCase()}</span>{row.project_name}</Link></td><td>{row.participant_names.join(", ")}</td><td><span className="confidence"><span className="confidence-track"><span style={{width:`${row.confidence}%`}}/></span>{row.confidence}%</span></td><td>{row.needs_review?<span className="status-pill queued"><span className="status-dot"/>Review</span>:<span style={{color:"#418469",fontSize:9}}>Clear</span>}</td><td><span className="score-pill">{row.total_score.toFixed(1)}</span></td><td><Link href={`/reports/${row.run_id}`} className="text-link" aria-label="Open report"><ArrowRight size={14}/></Link></td></tr>)}</tbody></table></div>:<div className="empty-state"><div><div className="empty-icon"><Trophy size={17}/></div><b>No completed scores yet</b>Run the judge on a project to add it to the leaderboard.<div style={{marginTop:12}}><Link href="/submissions" className="text-link">Browse projects <ArrowRight size={13}/></Link></div></div></div>}</div>
   <div className="panel" style={{marginTop:13}}><div className="bullet-row"><ShieldCheck size={14}/>Every entry links to its evaluation report, evidence and review flags.</div></div>
 </>;
}
